### ISSUE TITLE
[BUG] Digital Glitch will stop functioning correct with Media Source. Once you Hide/Show Media Source.

### ISSUE THREAD

**Issue by decors1** [FiniteSingularity/obs-retro-effects#33]
[Describe the bug]

If you Hide/Show Media Source, Digital Glitch no longer work until you reset filter settings.

[To Reproduce]

1. add a "Media Source" probably any kind of videos.
  (also checked with image & Noise and both works fine.)
3. add a "Retro Effects (Digital Glitch)" default is fine.
4. hide and show Media Source.
5. And the Digital Glitch stops functioning.

[Environment]

OS/Version: Windows 11
OBS Version: 30.1.2 (64bits)
Retro Effects: 0.0.10a

[GPU]

GPU make/model [RTX 4070]
GPU VRAM [12Gb]

**Comment by FiniteSingularity** [comment]
I've got a fix for this one as well, in PR #35  .  Issue was with the tick update- other sources when they are toggled off still report their dimensions as their original size.  Media sources, since they stop playing, report their size as zero, and I was trying to assign/index a zero-size vector.  You can check out the action build artifacts here if you want to test it: https://github.com/FiniteSingularity/obs-retro-effects/actions/runs/9243893741

**Comment by decors1** [comment]
#35 soleved Media Source issue.
But Matrix Rain issues are not fixed yet. It’s behaving the same as last time.

**Comment by FiniteSingularity** [comment]
Thanks for reporting these bugs and trying the PRs out.  I'll merge it all in and cut a 0.0.11 bugfix pre-release.
